/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "fragment AuthorFragment on Author {\n  id\n  name\n  avatar\n}\n\nfragment MomentFragment on Moment {\n  id\n  applauseCount\n  viewerApplauseCount\n  createdAt\n  updatedAt\n  isLocal\n  isBlurred\n  isLocked\n  hasAdultContent\n  sequence\n  type\n  videoThumbnailUrl\n  mediaUrl\n  hasViewerSeen\n  description\n  commentCount\n  mediaItems {\n    id\n    mediaUrl\n    mediaType\n    thumbnailUrl\n  }\n  author {\n    ...AuthorFragment\n  }\n}": typeof types.AuthorFragmentFragmentDoc,
    "mutation CreateInteraction($input: CreateInteractionInput!) {\n  createInteraction(input: $input)\n}\n\nmutation UpdateUserName($input: UpdateUserName!) {\n  updateUserName(input: $input) {\n    id\n    name\n    avatar\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    email\n  }\n}\n\nmutation UnblurMoment($input: UnblurMomentInput!) {\n  unblurMoment(input: $input) {\n    success\n    error\n  }\n}\n\nmutation CreateReport($input: CreateReportInput!) {\n  createReport(input: $input) {\n    success\n    error\n  }\n}\n\nmutation BlockAuthor($input: BlockAuthor!) {\n  blockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation UnblockAuthor($input: BlockAuthor!) {\n  unblockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation HideMoment($input: HideMoment!) {\n  hideMoment(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    hiddenMomentIds\n  }\n}\n\nmutation SaveDeviceToken($deviceToken: String!, $platform: String!) {\n  saveDeviceToken(deviceToken: $deviceToken, platform: $platform)\n}\n\nmutation SetNotificationAsRead($notificationId: ID!) {\n  setNotificationAsRead(notificationId: $notificationId)\n}": typeof types.CreateInteractionDocument,
    "query GetFeedMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getFeedMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetWalletBalance($authorId: ID!) {\n  getWalletBalance(authorId: $authorId) {\n    transferable\n    redeemable\n  }\n}\n\nquery GetInteractionsByMoment($momentId: ID!, $nextToken: String) {\n  interactionsByMoment(momentId: $momentId, nextToken: $nextToken) {\n    interactions {\n      viewerId\n      viewer {\n        id\n        name\n        avatar\n      }\n      applauseCount\n    }\n    nextToken\n  }\n}\n\nquery GetAuthorMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getAuthorMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetMoment($input: GetMomentInput!) {\n  getMoment(input: $input) {\n    ...MomentFragment\n  }\n}\n\nquery GetNotifications($limit: Int, $nextToken: String) {\n  getNotifications(limit: $limit, nextToken: $nextToken) {\n    items {\n      notificationId\n      title\n      message\n      type\n      isRead\n      createdAt\n      mediaUrl\n      userId\n      momentId\n      momentSequence\n      viewerId\n      viewerName\n      viewerAvatar\n    }\n    nextToken\n  }\n}": typeof types.GetFeedMomentsDocument,
    "subscription OnNewNotification($userId: ID!) {\n  onNewNotification(userId: $userId) {\n    title\n    notificationId\n    createdAt\n    type\n    message\n    isRead\n  }\n}": typeof types.OnNewNotificationDocument,
};
const documents: Documents = {
    "fragment AuthorFragment on Author {\n  id\n  name\n  avatar\n}\n\nfragment MomentFragment on Moment {\n  id\n  applauseCount\n  viewerApplauseCount\n  createdAt\n  updatedAt\n  isLocal\n  isBlurred\n  isLocked\n  hasAdultContent\n  sequence\n  type\n  videoThumbnailUrl\n  mediaUrl\n  hasViewerSeen\n  description\n  commentCount\n  mediaItems {\n    id\n    mediaUrl\n    mediaType\n    thumbnailUrl\n  }\n  author {\n    ...AuthorFragment\n  }\n}": types.AuthorFragmentFragmentDoc,
    "mutation CreateInteraction($input: CreateInteractionInput!) {\n  createInteraction(input: $input)\n}\n\nmutation UpdateUserName($input: UpdateUserName!) {\n  updateUserName(input: $input) {\n    id\n    name\n    avatar\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    email\n  }\n}\n\nmutation UnblurMoment($input: UnblurMomentInput!) {\n  unblurMoment(input: $input) {\n    success\n    error\n  }\n}\n\nmutation CreateReport($input: CreateReportInput!) {\n  createReport(input: $input) {\n    success\n    error\n  }\n}\n\nmutation BlockAuthor($input: BlockAuthor!) {\n  blockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation UnblockAuthor($input: BlockAuthor!) {\n  unblockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation HideMoment($input: HideMoment!) {\n  hideMoment(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    hiddenMomentIds\n  }\n}\n\nmutation SaveDeviceToken($deviceToken: String!, $platform: String!) {\n  saveDeviceToken(deviceToken: $deviceToken, platform: $platform)\n}\n\nmutation SetNotificationAsRead($notificationId: ID!) {\n  setNotificationAsRead(notificationId: $notificationId)\n}": types.CreateInteractionDocument,
    "query GetFeedMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getFeedMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetWalletBalance($authorId: ID!) {\n  getWalletBalance(authorId: $authorId) {\n    transferable\n    redeemable\n  }\n}\n\nquery GetInteractionsByMoment($momentId: ID!, $nextToken: String) {\n  interactionsByMoment(momentId: $momentId, nextToken: $nextToken) {\n    interactions {\n      viewerId\n      viewer {\n        id\n        name\n        avatar\n      }\n      applauseCount\n    }\n    nextToken\n  }\n}\n\nquery GetAuthorMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getAuthorMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetMoment($input: GetMomentInput!) {\n  getMoment(input: $input) {\n    ...MomentFragment\n  }\n}\n\nquery GetNotifications($limit: Int, $nextToken: String) {\n  getNotifications(limit: $limit, nextToken: $nextToken) {\n    items {\n      notificationId\n      title\n      message\n      type\n      isRead\n      createdAt\n      mediaUrl\n      userId\n      momentId\n      momentSequence\n      viewerId\n      viewerName\n      viewerAvatar\n    }\n    nextToken\n  }\n}": types.GetFeedMomentsDocument,
    "subscription OnNewNotification($userId: ID!) {\n  onNewNotification(userId: $userId) {\n    title\n    notificationId\n    createdAt\n    type\n    message\n    isRead\n  }\n}": types.OnNewNotificationDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment AuthorFragment on Author {\n  id\n  name\n  avatar\n}\n\nfragment MomentFragment on Moment {\n  id\n  applauseCount\n  viewerApplauseCount\n  createdAt\n  updatedAt\n  isLocal\n  isBlurred\n  isLocked\n  hasAdultContent\n  sequence\n  type\n  videoThumbnailUrl\n  mediaUrl\n  hasViewerSeen\n  description\n  commentCount\n  mediaItems {\n    id\n    mediaUrl\n    mediaType\n    thumbnailUrl\n  }\n  author {\n    ...AuthorFragment\n  }\n}"): (typeof documents)["fragment AuthorFragment on Author {\n  id\n  name\n  avatar\n}\n\nfragment MomentFragment on Moment {\n  id\n  applauseCount\n  viewerApplauseCount\n  createdAt\n  updatedAt\n  isLocal\n  isBlurred\n  isLocked\n  hasAdultContent\n  sequence\n  type\n  videoThumbnailUrl\n  mediaUrl\n  hasViewerSeen\n  description\n  commentCount\n  mediaItems {\n    id\n    mediaUrl\n    mediaType\n    thumbnailUrl\n  }\n  author {\n    ...AuthorFragment\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateInteraction($input: CreateInteractionInput!) {\n  createInteraction(input: $input)\n}\n\nmutation UpdateUserName($input: UpdateUserName!) {\n  updateUserName(input: $input) {\n    id\n    name\n    avatar\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    email\n  }\n}\n\nmutation UnblurMoment($input: UnblurMomentInput!) {\n  unblurMoment(input: $input) {\n    success\n    error\n  }\n}\n\nmutation CreateReport($input: CreateReportInput!) {\n  createReport(input: $input) {\n    success\n    error\n  }\n}\n\nmutation BlockAuthor($input: BlockAuthor!) {\n  blockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation UnblockAuthor($input: BlockAuthor!) {\n  unblockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation HideMoment($input: HideMoment!) {\n  hideMoment(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    hiddenMomentIds\n  }\n}\n\nmutation SaveDeviceToken($deviceToken: String!, $platform: String!) {\n  saveDeviceToken(deviceToken: $deviceToken, platform: $platform)\n}\n\nmutation SetNotificationAsRead($notificationId: ID!) {\n  setNotificationAsRead(notificationId: $notificationId)\n}"): (typeof documents)["mutation CreateInteraction($input: CreateInteractionInput!) {\n  createInteraction(input: $input)\n}\n\nmutation UpdateUserName($input: UpdateUserName!) {\n  updateUserName(input: $input) {\n    id\n    name\n    avatar\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    email\n  }\n}\n\nmutation UnblurMoment($input: UnblurMomentInput!) {\n  unblurMoment(input: $input) {\n    success\n    error\n  }\n}\n\nmutation CreateReport($input: CreateReportInput!) {\n  createReport(input: $input) {\n    success\n    error\n  }\n}\n\nmutation BlockAuthor($input: BlockAuthor!) {\n  blockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation UnblockAuthor($input: BlockAuthor!) {\n  unblockAuthor(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    blockedAuthorIds\n  }\n}\n\nmutation HideMoment($input: HideMoment!) {\n  hideMoment(input: $input) {\n    id\n    email\n    name\n    isAdult\n    hasIdentityValidation\n    allowAdultContent\n    hiddenMomentIds\n  }\n}\n\nmutation SaveDeviceToken($deviceToken: String!, $platform: String!) {\n  saveDeviceToken(deviceToken: $deviceToken, platform: $platform)\n}\n\nmutation SetNotificationAsRead($notificationId: ID!) {\n  setNotificationAsRead(notificationId: $notificationId)\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetFeedMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getFeedMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetWalletBalance($authorId: ID!) {\n  getWalletBalance(authorId: $authorId) {\n    transferable\n    redeemable\n  }\n}\n\nquery GetInteractionsByMoment($momentId: ID!, $nextToken: String) {\n  interactionsByMoment(momentId: $momentId, nextToken: $nextToken) {\n    interactions {\n      viewerId\n      viewer {\n        id\n        name\n        avatar\n      }\n      applauseCount\n    }\n    nextToken\n  }\n}\n\nquery GetAuthorMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getAuthorMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetMoment($input: GetMomentInput!) {\n  getMoment(input: $input) {\n    ...MomentFragment\n  }\n}\n\nquery GetNotifications($limit: Int, $nextToken: String) {\n  getNotifications(limit: $limit, nextToken: $nextToken) {\n    items {\n      notificationId\n      title\n      message\n      type\n      isRead\n      createdAt\n      mediaUrl\n      userId\n      momentId\n      momentSequence\n      viewerId\n      viewerName\n      viewerAvatar\n    }\n    nextToken\n  }\n}"): (typeof documents)["query GetFeedMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getFeedMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetWalletBalance($authorId: ID!) {\n  getWalletBalance(authorId: $authorId) {\n    transferable\n    redeemable\n  }\n}\n\nquery GetInteractionsByMoment($momentId: ID!, $nextToken: String) {\n  interactionsByMoment(momentId: $momentId, nextToken: $nextToken) {\n    interactions {\n      viewerId\n      viewer {\n        id\n        name\n        avatar\n      }\n      applauseCount\n    }\n    nextToken\n  }\n}\n\nquery GetAuthorMoments($authorId: ID!, $nextToken: String, $limit: Int) {\n  getAuthorMoments(authorId: $authorId, nextToken: $nextToken, limit: $limit) {\n    items {\n      ...MomentFragment\n    }\n    nextToken\n    resultCount\n  }\n}\n\nquery GetMoment($input: GetMomentInput!) {\n  getMoment(input: $input) {\n    ...MomentFragment\n  }\n}\n\nquery GetNotifications($limit: Int, $nextToken: String) {\n  getNotifications(limit: $limit, nextToken: $nextToken) {\n    items {\n      notificationId\n      title\n      message\n      type\n      isRead\n      createdAt\n      mediaUrl\n      userId\n      momentId\n      momentSequence\n      viewerId\n      viewerName\n      viewerAvatar\n    }\n    nextToken\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "subscription OnNewNotification($userId: ID!) {\n  onNewNotification(userId: $userId) {\n    title\n    notificationId\n    createdAt\n    type\n    message\n    isRead\n  }\n}"): (typeof documents)["subscription OnNewNotification($userId: ID!) {\n  onNewNotification(userId: $userId) {\n    title\n    notificationId\n    createdAt\n    type\n    message\n    isRead\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;